### ISSUE TITLE
Will there be any problems if there is a lot of data?

### ISSUE THREAD

**Issue by pengmingjun08** [stothard-group/cgview-js#11]
The documentation says：Capable of drawing genomes up to 10 Mbp with 1000's of features and 100's contigs
If there are 20 million data and 20,000 features, will there be any problems?
Thanks

**Comment by sciguy** [comment]
There is no hard limit to the sequence length or number of features. But as you increase either, there can be performance issues. We've had maps with 100,000's of features and they still work, however, the drawing time of the full map will be slower. Once you zoom in on a region, reducing the number of visible features, the drawing time will speed up.

**Comment by pengmingjun08** [comment]
Thank you
