### ISSUE TITLE
“gc-skew gc-content” It was moved to the maximum before drawing was completed, and there was a problem after moving it.

### ISSUE THREAD

**Issue by pengmingjun08** [stothard-group/cgview-js#13]
![20231105-000736](https://github.com/stothard-group/cgview-js/assets/56865100/816156c9-fa87-4e8b-91e8-a67252a30c69)
![20231105-000733](https://github.com/stothard-group/cgview-js/assets/56865100/155f04ed-26f5-4781-8aa4-176d27850fcc)
"gc-content gc-skew" has not been drawn to the maximum magnification. After completion, the sequence gap will be very large, and then it will go blank after moving it. Your demo will also have this problem.
And even if it is not maximized, after "gc-content gc-skew" is completed, the canvas will appear or be partially offset.

**Comment by pengmingjun08** [comment]
![20231105-002342](https://github.com/stothard-group/cgview-js/assets/56865100/940c26ac-23d3-4937-bf43-f39236aeb0d6)
![20231105-002344](https://github.com/stothard-group/cgview-js/assets/56865100/d9b79ba1-7cd9-454e-b87e-629c82ea978d)
![20231105-002340](https://github.com/stothard-group/cgview-js/assets/56865100/13e03102-a6af-4403-98f1-e73800d5a313)

Problem implementation steps:
1. Zoom in
2. Move
3. Blank

**Comment by pengmingjun08** [comment]
This is your demo

**Comment by pengmingjun08** [comment]
The above examples are all from the demo on your official website。I have another question to ask you. I need to perform operations on the sequence, such as adding, deleting, and replacing. After each operation, the canvas needs to be redrawn, which is time-consuming. Is there any idea that can guide me? Thank you. .

**Comment by pengmingjun08** [comment]
![20231107-110108](https://github.com/stothard-group/cgview-js/assets/56865100/e6150f57-ee5d-43a0-98a8-ae171ffdb1b4)
And after resetting, the initial image proportion is very large

**Comment by pengmingjun08** [comment]
![20231107-110328](https://github.com/stothard-group/cgview-js/assets/56865100/90bb1bd4-8ef8-4ff2-ac2f-a9cfb4157a31)
After resetting, the canvas can be seen, but the initial image scale is very large

**Comment by pengmingjun08** [comment]
After the first drawing is completed, zoom in on the canvas scale and then execute loadJSON() again to load new data. If the canvas scale is incorrect, as shown in the figure in step 4

**Comment by pengmingjun08** [comment]
After the first drawing is completed, zoom in on the canvas scale and then execute loadJSON() again to load new data. However, the canvas scale is incorrect, as shown in the figure in step 4

**Comment by sciguy** [comment]
Thanks @pengmingjun08 for documenting this issue. I've seen a similar scale problem when adding tracks while zoomed in. I believe it has to do with how `maxZoomFactor` is calculated. I will look into this next week.

**Comment by pengmingjun08** [comment]
@sciguy I'm glad to be able to help you

**Comment by sciguy** [comment]
I believe this is fixed in 6a341a2. The code in `docs/dist/cgview.min.js` has this fix applied.

Please try it out and see if you have any more problems.

**Comment by pengmingjun08** [comment]
@sciguy The problem has been resolved。You're so amazing ！
