### ISSUE TITLE
In Safari browser, there are instances where it crashes, freezes entirely, and this issue occurs consistently

### ISSUE THREAD

**Issue by pengmingjun08** [stothard-group/cgview-js#16]
![20240306-175148](https://github.com/stothard-group/cgview-js/assets/56865100/07668ee6-aa72-472e-9f7c-cf12f263e966)

The issue persists even when testing on the official website demo

**Comment by pengmingjun08** [comment]
Sometimes it can be loaded, but the entire website cannot be operated, just like opening a dead loop in the code

**Comment by sciguy** [comment]
Thanks for bringing this to my attention. It is fixed in e8b0b99

**Comment by pengmingjun08** [comment]
> Thanks for bringing this to my attention. It is fixed in [e8b0b99](https://github.com/stothard-group/cgview-js/commit/e8b0b9929812364f597c60cd75143510625c8741)

The performance in Safari browser is still like opening a dead loop

**Comment by pengmingjun08** [comment]
![image](https://github.com/stothard-group/cgview-js/assets/56865100/34826e78-ee32-48aa-bc2c-f440435cccc1)
When using Safari browser to open your official website, it crashes

**Comment by pengmingjun08** [comment]
> Thanks for bringing this to my attention. It is fixed in [e8b0b99](https://github.com/stothard-group/cgview-js/commit/e8b0b9929812364f597c60cd75143510625c8741)

https://github.com/stothard-group/cgview-js/assets/56865100/b3a47c08-8bdc-4572-9e08-891be708448b


Due to video size limitations, I can only record for such a long time. Let me describe my operation. After entering the website, the entire website froze for about 30 seconds, and no operations could be performed in the middle. After loading it, as described in the video, as long as you drag it for a while, the entire website will freeze and no operations can be performed

**Comment by pengmingjun08** [comment]
In Safari browser

**Comment by sciguy** [comment]
Oh, it looks like you are using Safari 17.1. Unfortunately there is a bug in Safari 17.1 (and 17.0) that causes a slow down when drawing the plots (e.g. GC Content). Fortunately, the bug was fixed in Safari 17.2.

Try upgrading your Safari browser or using a different browser (we never saw the issue in Chrome or Firefox).

**Comment by pengmingjun08** [comment]
> Oh, it looks like you are using Safari 17.1. Unfortunately there is a bug in Safari 17.1 (and 17.0) that causes a slow down when drawing the plots (e.g. GC Content). Fortunately, the bug was fixed in Safari 17.2.
> 
> Try upgrading your Safari browser or using a different browser (we never saw the issue in Chrome or Firefox).


Thank you for your answer
