### ISSUE TITLE
Pinch zoom gesture, zooming not centred on touch site

### ISSUE THREAD

**Issue by paulstothard** [stothard-group/cgview-js#5]
A two-point pinch gesture zooms but the zoom position is not located at the touch site (unlike when zooming is done using the mouse pointer). [This link](https://stackoverflow.com/questions/45108732/drawing-on-html5-canvas-with-support-for-multitouch-pinch-pan-and-zoom) provides a demo where pinch zooming works well.

**Comment by sciguy** [comment]
This has been fixed in commit 64a2009.
