### ISSUE TITLE
Show more content

### ISSUE THREAD

**Issue by qkqk-hub** [stothard-group/cgview-js#6]
I'm showing you a little bit now, I want to show you a little bit more so how do I change the code, or where do I change the code? Like the picture below:
![CGV](https://github.com/stothard-group/cgview-js/assets/54273704/4dee8878-2303-4828-8102-2520fbf4f027)

**Comment by sciguy** [comment]
The easiest way to add more content to the popups is to add the data to the feature meta data. Any meta data will (by default) be shown as key/value pairs in the popup. For example, to add more info to the first feature:

```js
cgv.features(1).meta = {'COG_Classification': 'COG Unavailable'}
```

For even more control, you can add your own custom popup contents:

```js
cgv.highlighter.feature.popoverContents = (cgvEvent) => {
  const feature = cgvEvent.element;
  return `<div>The start position is ${feature.start} bp</div>`
}
```

For more on what cgvEvent contains see [CGView.js events](https://js.cgview.ca/api/EventMonitor.html).

**Comment by qkqk-hub** [comment]
Thank you very much for your reply！
I have successfully implemented this function.
Now I have the following two questions, please help me to answer, Thank you!:
1.

- **My current situation:There is only one track on either side of the backbone.**

![image](https://github.com/stothard-group/cgview-js/assets/54273704/658316ee-5d7a-4776-b3e4-2abced9b563f)

- **I want to achieve the situation：There are multiple tracks on both sides of the backbone.**

![image](https://github.com/stothard-group/cgview-js/assets/54273704/7198f452-5391-4456-8dbc-f9769144d8b1)

2.

- **My current situation:There are many white gaps on backbone, how to remove this one?**

![image](https://github.com/stothard-group/cgview-js/assets/54273704/e4c2cfb2-aed2-4420-bbfc-72ee57a20f41)

- **I want to achieve the situation：Remove white gaps on backbone.**

![image](https://github.com/stothard-group/cgview-js/assets/54273704/b3852b9f-dd41-4a40-ba70-0960b148377e)

**Thanks again!**

**Comment by sciguy** [comment]
1) Are you wanting a separate slot for each reading frame in a track. If that's the case, set the track `separateFeaturesBy` to "readingFrame":

```js
cgv.tracks(1).update({separateFeaturesBy: 'readingFrame'})
```

2) The white gaps on the backbone indicate a contig boundary. Does you sequence have multiple contigs? If so, then the gaps are normal and not removable. If not, then it's a bug, in which case send me your cgview json and I can look into the issue. You can generate your cgview json with the following command:

```js
cgv.io.downloadJSON()
```

**Comment by qkqk-hub** [comment]
Hello, it's time to communicate again, I'm glad to ask you questions, thank you very much!
1. The first problem has been solved with your help.
2. I get it: my sequence does have multiple contigs.

I met a new problem today, please help me again.

Here is the gbk file I got using prokka:

![image](https://github.com/stothard-group/cgview-js/assets/54273704/1f98468b-c4ca-4576-9a19-811cd69e0484)

I want to show COG's function and protein sequence, but the json file I generated by cgview_builder_cli.rb and config_example.yaml does not contain COG's function and protein sequence information. May I ask what I should do? Do I need to modify the config_example.yaml file?

Thanks!

**Comment by sciguy** [comment]
The `cgview_builder_cli.rb` script does not copy all the feature information. That would make the resulting JSON file larger than it needs to be. I would suggest manually editing the `cgview_builder_cli.rb` script to grab the tags you want. Having the tags to copy in the `config_example.yaml` is a great idea for future version.

I would also recommend starting a new GitHub issue for future questions.

**Comment by qkqk-hub** [comment]
Thanks for your advice, I have got the json file I want by modifying the cgview_builder_cli.rb script
