### ISSUE TITLE
Identify the newly added information in json

### ISSUE THREAD

**Issue by qkqk-hub** [stothard-group/cgview-js#7]
Hello, I got the json file I wanted by modifying the cgview_builder.rb script, below is a screenshot of my json file, cog and translation information in features was added by me manually:

![image](https://github.com/stothard-group/cgview-js/assets/54273704/93b90956-70d6-4915-b06b-198a9a48da22)

Now I have a problem, after the json file is loaded into cgv, it cannot recognize the new json information I added, such as cog and translation information cannot be recognized

![image](https://github.com/stothard-group/cgview-js/assets/54273704/804e2843-c023-46f4-b2b7-03e2d0065d3c)

The content of ${feature-cog} is undefined, I tried to modify the cgview.esm.js file, but I did not know where to modify it, may I ask what I should do? Thanks!

**Comment by sciguy** [comment]
Sorry, I should have mentioned this early. It’s best not to add additional attributes directly to the feature. Extra feature properties will not be imported from the JSON. Instead, add them to the feature’s meta property:

`feature.meta = {cog: ‘cogName’}`

The meta object and any key/values you add will be imported from the JSON.

**Comment by sciguy** [comment]
Sorry, I should have mentioned this early. It’s best not to add additional attributes directly to the feature. Extra feature properties will not be imported from the JSON. Instead, add them to the feature’s meta property:

`feature.meta = {cog: ‘cogName’}`

The meta object and any key/values you add will be imported from the JSON.

**Comment by qkqk-hub** [comment]
That's okay. Oh, I see. I have realized this function according to the method you mentioned. Thank you very much!

I had a new problem. I wanted to stain each gene according to its COG_Categories, 26 colors in 26 categories.

1. 
I made a preliminary attempt to divide the gene color into two parts. If the cog content is Not Available, it is the default color; if the cog content starts with COG, the color is rgb(51,51,51). But it has not taken effect, may I ask how I should modify my code?Here is a screenshot of my code:
![image](https://github.com/stothard-group/cgview-js/assets/54273704/2d48cf1a-f364-4139-bd84-d6894d44504f)

2.
I used the gbk file generated by prokka software, COG format is: /db_xref="COG:COG0506". If I want to stain genes according to COG's A-Z, do I need to manually modify my gbk file? Or is there a better way to do it?The ideal effect is shown below:

![image](https://github.com/stothard-group/cgview-js/assets/54273704/2e8f30cf-0e9f-42e9-a13e-e394900bab44)

Thanks again!

**Comment by qkqk-hub** [comment]
Sorry to bother you, but I have another problem:

3.

I want to add a new track to my CGView to represent the information of mobile genetic elements, but the corresponding pattern is not displayed in the newly added track. Here is my WEB page effect, HTML code, json file:

WEB page effect：The outermost track does not produce a pattern.

![image](https://github.com/stothard-group/cgview-js/assets/54273704/ef8c8cce-f8da-40f9-b90a-1127311f94a6)

HTML code：

![image](https://github.com/stothard-group/cgview-js/assets/54273704/961b1ddc-958b-46aa-86e1-6ccd55df002e)

json file：

![image](https://github.com/stothard-group/cgview-js/assets/54273704/72584623-6749-4570-9743-0a3021e4bf5a)

Thank you very much for your help!

**Comment by qkqk-hub** [comment]
Hello, I have solved the first question.
He dyed according to legend, thank you for your help before, I will close this problem, and I will consult you if I have any questions in the future, thank you!
