### ISSUE TITLE
Change the Labels font color

### ISSUE THREAD

**Issue by qkqk-hub** [stothard-group/cgview-js#8]
Hello, I want to make the Labels font color correspond to its feature color, here is my code:
![image](https://github.com/stothard-group/cgview-js/assets/54273704/13793568-5eba-4068-8f75-223f40dcaee9)
I give each label a color iteratively and print the _rgbaString property on the console to make sure it has been given a color, but why is the label font color on the page still black? Nothing has changed, please help me! Thanks!
![image](https://github.com/stothard-group/cgview-js/assets/54273704/35c35d79-26c5-4c3c-8101-6462342ca234)

**Comment by sciguy** [comment]
There is only one annotation object in CGView.js. For the annotation, the color can be set to one specific color or it can be undefined. When the color is undefined, the feature color will automatically be used. The following code will make the labels the same color as the feature:

```js
cgv.annotation.update({
  color: undefined
});
```

**Comment by qkqk-hub** [comment]
Thank you very much. According to your method, this problem has been solved
