### ISSUE TITLE
Error "d3 is not defined" when importing from IIFE

### ISSUE THREAD

**Issue by maxfieldegaj** [stothard-group/cgview-js#9]
I'm trying to use CGView in a NextJS(_version 13.4.4_) app, and getting the error `d3 is not defined (at .../node_modules/cgview/dist/cgview.js (19502:7)` from the following code.

```
import CGV from 'cgview/dist/cgview.js';

export const SchemaPlasmidMap = new CGV.Viewer('#my-viewer', {
  height: 500,
  width: 500,
  sequence: {
    // The length of the sequence
    length: 1000,
  },
});

```

I've confirmed that `d3` was installed within the `cgview`  node modules. 

When trying to import from the ESM, I get a different error from within CGView (#10 ).

**Comment by sciguy** [comment]
The IIFE versions (dist/cgview.js & dist/cgview.min.js) are meant to be added as script tags to a project with d3 being sourced first:

```html
<script src="https://d3js.org/d3.v7.min.js"></script>
<script src="PATH/TO/cgview.min.js"></script>
```

And then accessed via the global CGV:
```js
cgv = new CGV.Viewer('#my-viewer', {OPTIONS});
```

That is how it is used on the js.cgview.ca site.

**Comment by maxfieldegaj** [comment]
> The IIFE versions (dist/cgview.js & dist/cgview.min.js) are meant to be added as script tags to a project with d3 being sourced first:
> 
> ```
> <script src="https://d3js.org/d3.v7.min.js"></script>
> <script src="PATH/TO/cgview.min.js"></script>
> ```
> 
> And then accessed via the global CGV:
> 
> ```js
> cgv = new CGV.Viewer('#my-viewer', {OPTIONS});
> ```
> 
> That is how it is used on the js.cgview.ca site.

That makes sense. I was trying the method I described above as a fallback before resolving #10 . Appreciate the responsiveness to both!
